### ISSUE TITLE
Can't start monitoring

### ISSUE THREAD

**Issue by diversenok** [zodiacon/ProcMonX#3]
**OS**: Windows 7 x64 (English)
**ProcMonX**: 0.21

When I press "Start Monitoring" this happens:

	Fatal error: Cannot create a file when that file already exists. (Exception from HRESULT: 0x800700B7).
	   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
	   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
	   at ProcMonX.Tracing.TraceManager.<>c__DisplayClass8_0.<Start>b__0() in C:\Dev\ProcMonX\ProcMonX\Tracing\TraceManager.cs:line 50
	   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.ThreadHelper.ThreadStart()

And then ProcMonX crashes.

If it can help I can send you Sysinternal's Process Monitor log that captures this event.

**Comment by zodiacon** [comment]
I tested this version on a x64 Windows 7 VM and it works ok. Do send me that log, maybe will help me.
Does it work for you on Win 10?

**Comment by diversenok** [comment]
I've sent the logs. And I've tested ProcMonX on another machine with Win 7 x64, the behavior is the same. On Windows 10 RS1 x86 it works fine.

**UPD:** Oh, sorry, I didn't notice your reply to the email:
> My best guess is this: On Windows 7 there can be only one ETW session that registers for the Kernel provider.
You might have some other program that has an open session, and so ProcMonX fails.
You can look at Event Trace Sessions under Data Collector Sets under Performance (run perfmon to get there quickly).

Honestly, I don't know what it means but looks like I've found the reason for that problem: it happens only when I have Process Hacker running on the machine.
